version: '3'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "wG>wNwFbdD!*6kZv"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
#SSMS: localhost,1433 : sa : SA_PASSWORD